version: '2'

volumes:
  postgresql_data:

services:
  server:
    command: postgres -c config_file=/config/postgresql.conf -c hba_file=/config/pg_hba.conf
    environment:
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minha_senha
    image: postgres:9.5.13-alpine
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - /etc/opt/postgresql/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - /etc/opt/postgresql/postgresql.conf:/config/postgresql.conf
      - /etc/opt/postgresql/pg_hba.conf:/config/pg_hba.conf
      - /etc/letsencrypt/live/demo.bortes.me/cert.pem:/certs/demo.bortes.me/cert.pem
      - /etc/letsencrypt/live/demo.bortes.me/privkey.pem:/certs/demo.bortes.me/key.pem